### ISSUE TITLE
It would be great to see some simple examples

### ISSUE THREAD

**Issue by yatsek-sando** [NeilGirdhar/tikzify#1]
Like in the title.
Your library looks really interesting but I have problems with using it. Is there possibility to see some examples? - at least minimal one.

**Comment by NeilGirdhar** [comment]
@yatsek-sando Yes, I am happy to put something together for you.  Give me a couple days please and I will have something up for you.

**Comment by NeilGirdhar** [comment]
@yatsek-sando I've added an example.  Could you try to build it and let me know how it goes?
